version: "3.8"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['initial_root_password'] = 'Abcd@0123456789'
        puma['worker_processes'] = 0 # disable cluster mode to avoid more memory usage
    ports:
      - "8443:443"
      - "8080:80"
      - "8022:22"
    restart: always
    volumes:
      - ./gitlab/config:/etc/gitlab:z
      - ./gitlab/logs:/var/log/gitlab:z
      - ./gitlab/data:/var/opt/gitlab:z
      - /etc/localtime:/etc/localtime
# (Options)
    # sysctls:
    #   net.core.somaxconn: 1024
    # ulimits:
    #   sigpending: 62793
    #   nproc: 131072
    #   nofile:
    #     soft: 60000
    #     hard: 60000
    #   core: 0
